site_url : https://asalvadorc.github.io/BBDD_POSTGRESQL
site_name: BD - Bases de Dades
theme: 
  name: readthedocs
  logo: assets/logocaminas.png

extra_css:
  - css/extra.css
  - img/favicon.ico 
nav:
  
  - SQL - POSTGRES:
    - Objectius i Coneixements previs: BD_PostgreSQL_DQL/objectius_i_coneixements_previs.md
    - 1. Introducció: BD_PostgreSQL_DQL/1_introducci.md
    - 2. DBeaver: BD_PostgreSQL_DQL/2_client_dbeaver_installaci_i_confiuraci.md
    - 3 Dades dels exemples i els exercicis: BD_PostgreSQL_DQL/3_dades_dels_exemples_i_els_exercicis.md
    - 4. Operadors i Funcions de Postgres:
      - 4.1. Operadors: BD_PostgreSQL_DQL/6_operadors.md
      - 4.2. Funcions: BD_PostgreSQL_DQL/7_funcions.md
    - DQL Consultes (part I):  
      - 1. La consulta SELECT: BD_PostgreSQL_DQL/1_la_consulta_select.md
      - 2. Consulta bàsica: BD_PostgreSQL_DQL/2_consulta_bsica.md
      - 3. Àlies en les columnes: BD_PostgreSQL_DQL/3_lies_en_les_columnes.md
      - 4. La clàusula WHERE: BD_PostgreSQL_DQL/4_la_clusula_where.md       
      - 5. Funcions d'agregat: BD_PostgreSQL_DQL/5_funcions_dagregat.md     
      - 6. La clàusula GROUP BY: BD_PostgreSQL_DQL/6_la_clusula_group_by.md      
      - 7. La clàusula HAVING: BD_PostgreSQL_DQL/7_la_clusula_having.md    
      - 8. La clàusula ORDER BY: BD_PostgreSQL_DQL/8_la_clusula_order_by.md 
      - 9. El predicat DISTINCT: BD_PostgreSQL_DQL/9_el_predicat_distinct.md  
      - 10. La clàusula LIMIT .. OFFSET: BD_PostgreSQL_DQL/10_la_clusula_limit__offset.md  
      - 11. Consulta de creació de taules: BD_PostgreSQL_DQL/11_consulta_de_creaci_de_taules.md
      - 12. Ordre amb que s'executa una sentència SQL: BD_PostgreSQL_DQL/12_ordre_amb_qu_sexecuta_una_sentncia_sql.md
      - Exercicis amb els resultats (part I): BD_PostgreSQL_DQL/exercicis_de_tot_el_tema_amb_els_resultats.md    
    - DQL Consulta avançades (part II):
      - 1. Introducció: BD_PostgreSQL_DQL_Avancat/21_introducci.md
      - 2. Combinacions de taules: BD_PostgreSQL_DQL_Avancat/22_combinacions_de_taules.md
      - 3. Subconsultes: BD_PostgreSQL_DQL_Avancat/23_subconsultes.md
      - 4. Consultes d'operacions de conjunts: BD_PostgreSQL_DQL_Avancat/24_consultes_doperacions_de_conjunts.md  
      - Exercicis amb els resultats (part II): BD_PostgreSQL_DQL_Avancat/exercicis_de_tot_el_tema_amb_els_resultats.md

        